const mongoose= require('mongoose');
const Schema =mongoose.Schema;
const NurseSchema=new Schema({
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    nurseID:{
        type:String,
        required:true
    },
    phoneNumber:{
        type:String,
        required:false
    },
    email:{
        type:String,
        required:false
    },
    nursingLicenseNo:{
        type:String,
        required:false
    },
    specialization:{
        type:String,
        required:false
    },
    professionalExperience:{
        type:String,
        required:false
    },
    address:{
        type:String,
        required:false
    },
    avalibleDays:{
        type:String,
        required:false
    },
    emergencyContactNumbers:{
        type:String,
        required:false
    },
    gender:{
        type:String,
        required:false
    },
    relationship:{
        type:String,
        required:false
    },
    skillsAndTraining:{
        type:Object,
        required:false
    }
})
const Nurse=mongoose.model("Nurse",NurseSchema);
module.exports=Nurse;